src/components/Outcomes/OutcomePanel/OutcomePanel.tsx, src/components/Prompts/CurrentPrompt/CurrentPrompt.tsx, src/components/Prompts/PromptPanel/PromptPanel.tsx, src/components/ui/HexagonCollection/HexagonCollection.tsx, src/components/ui/HexagonItem/HexagonItem.tsx, src/components/ui/Layout/TwoColumnLayout.tsx, src/pages/prompt.tsx
This PR includes:
- Styling improvements related to Mobile and the Hexagons (or various elements related to them).
- Commented out the hexagons that we don't use.  Technically CDP is not in use, but it could be with another change, so I left that in there future now.  Current options are XMC, Personalize, CDP, Send, Order Cloud, and Search.
=> Feature remove unnecessary hexagons temporarily

src/components/ui/Layout/SingleColumnLayout.tsx, src/lib/NextPrompts.ts
Found a missing question that needed to be there (Search) and found a bug and fixed it.  While at it, I found the one column layout used on the settings page, was not consistent with the padding as the two column.  Both should be resolved.
To see the Search Question, you need to answer "XM" in the quiz.  To see other products if you are curious, Personalize shows up if you select XP and Historical Personalization.  Send will show up if you select XP and Marketing Automation from the features.  Lastly Order Cloud will show up if you select XC.
=> Bug Fixes related to a missing question

src/lib/GameContextParser.ts, src/models/OutcomeConditions.ts, src/models/PromptMappings.ts
In order to make it easier to test and to extend, the parsing logic from OutcomeConditions has been moved to a separate library. OutcomeConditions now only has the data and the business logic related to that data. Parsing logic is now fully in GameContextParser.
Side fix was to eliminate the duplicate PromptMappings enum. Now everything uses the PromptMappings from the Models folder.
=> Moved parsing logic to new GameContextParser library

src/components/ui/Layout/TwoColumnLayout.tsx, src/components/ui/Loading/Loading.tsx, src/components/ui/Settings/Settings.tsx
This change fixes two bugs:
- Improve the UI of the Loading Animation
- Apply that animation across the app
- Update the logic to activate the loading animation when you select a theme, and then wait for persona/avatars to load.
- Tested in various mobile and desktop sizes.
=> Loading Animation fixes

src/components/Outcomes/OutcomePanel/OutcomePanel.tsx, src/components/ui/FeedbackModal/FeedbackModal.tsx, src/components/ui/Layout/Layout.tsx, src/components/ui/Layout/SingleColumnLayout.tsx, src/components/ui/Layout/TwoColumnLayout.tsx, src/components/ui/Navigation/Navigation.tsx, src/pages/index.tsx, src/pages/outcome.tsx, src/pages/prompt.tsx
I'm sure there will be lots of comments here:
- Feedback pops up on Outcome page after 5 seconds (we can change this value, should it be longer, shorter, or not exist at all)?
- How about the text here in the modal?  Does it need work? Suggestions welcome.
- Feedback button in navigation does not display on the outcome page (since we have an outcome popup) (Should it or should it still show up anyway)
- The feedback button shows up only in larger screen sizes everywhere else.  In fantasy, because the button is larger, we have to only show at the largest screen sizes.
- Feedback button opens new tab/window with form in it.
- Is there anywhere you think the button or modal should be or shouldn't be?
=> Added Feedback functionality

src/components/Outcomes/OutcomePanel/OutcomePanel.tsx, src/components/ui/InfoModal/InfoModal.tsx
Added to GA/CDP the tracking of outcome answers (answers that got to this outcome).  Can't really see the data locally currently, since both GA/CDP take a while to process event data like this, but not seeing any errors and will make another change if needed after this PR is approved, if needed.
This also includes the update to About Info Modal, to include a reference to CDP/Personalize.  Will keep it simple for now.
=> Added additional logging of answers for CDP/GA

src/chakra/theme/corporate/button.ts, src/components/ui/ThemeSwitcher/ThemeSwitcher.tsx
Previously it was difficult to tell in the Persona list and Multi Select which options where active. 
Before: 
With Change:
I attempted to limit the scope to just the solid button variants which is what is being used on persona list and multi select. This has also been organized into the chakra/theme folder so if we need future overrrides on buttons or other corporate components they can go there as well.
=> Overriding Sitecore Theme isActive with a darker color

.github/workflows/component.yml, .github/workflows/e2e.yml, cypress/e2e/OutcomeFlow/outcome.cy.ts, cypress/e2e/Themes/theme.cy.ts, src/components/ui/Layout/SingleColumnLayout.tsx, src/components/ui/PersonaList/PersonaList.tsx
A poorly named branch because one test is for the outcome page while the second is for theme switching. 
But two additional e2e tests. We should talk more on how we want to build these out and what sort of coverage we are interested in.
=> Two new e2e tests

src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx, src/lib/GameContextParser.ts, src/models/OutcomeConditions.ts
Fixes #90 
Added two articles and a video, as defined in #90 . The video and the Spektor article show for all outcomes, and the San Filippo article only displays if the user specifies that they currently have a non-headless framework for their implementation.
=> 90 add community articles

cypress/e2e/OutcomeFlow/outcome.cy.ts, src/GraphQL/Queries/Outcome.gql, src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx, src/models/IOutcome.ts, src/models/IOutcomeReason.ts, src/models/index.ts
Adds new queries to pull in "outcome reasons" from Content Hub ONE. Each outcome reason has a text which explains why a particular product is needed for the migration. The Outcome Generator will display reasons for the products that are recommended.
Fixes #97
=> 97 add product recommendation reasons

src/components/ui/LinkCard/LinkCard.tsx
Essentially added the mechanism to track clicks on external links to both Google Analytics and CDP.  I've confirmed this works with CDP, however not seeing the data in Analytics yet, but that's not entirely surprising since it does seem to have a delay.
Didn't need to block the ui, since all the guides open in a new window.
=> Added tracking of external link click for guides

src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx, src/components/ui/LinkCard/LinkCard.tsx
XMC content migration tool now shows for all users on the outcome page. Also added an optional button text for the LinkCard so we can change it from the default.
=> Adding XM Cloud migration tool to the outcome page

src/components/Prompts/CurrentPrompt/CurrentPrompt.tsx, src/components/Prompts/MultiSelect/MultiSelect.tsx
Since we were using the same reference of MultiSelect across prompts, we needed to add a useEffect, to set the selectedOptions back to empty as the prompt changes.  I thought this was a missing dependency array for a useEffect, but in this case, it was a missing useEffect that was needed.
=> Fix for Validation Issue after previous multi-select

src/components/Outcomes/OutcomePanel/OutcomePanel.tsx
Added Google Analytics tracking and Engage SDK tracking for recommended products.  This gets logged as a custom event on the outcome page when it loads.  I was able to confirm this getting logged in both analytics tools.
=> Implemented tracking of recommended products

src/components/Contexts/EngageTrackerContext/EngageTrackerContext.tsx, src/pages/index.tsx
Forgot this was the first time I implemented Engage, and Developer Portal was after.  I learned on the Developer Portal implementation that if you enforce the cookie, then Vercel just doesn't work correctly, and you'd want the value to not be set (and then it works fine).  And because I wasn't setting it, that's why I was getting that error of it not being configured correctly.
So long story short, this removes that requirement, so now this should work in all Vercel preview environments as well as in production.
To test, make sure you can go to the environment, make sure nothing extra is displaying that you wouldn't expect, and then go into the console and type `Engage.getBrowserId()` and make sure it returns an Id.  If you would like to take that further, send it to me and I'll send over …
=> Make sure Cookie isn't Enforced

src/components/ui/LandingPage/LandingPage.tsx
Current Step 4 is not implemented (no signup form). Replacing text with words to direct the user towards providing us feedback.
=> Landing page: Changing Step 4 from email signup to providing feedback

src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx
On the Outcome page, will now show a community guide for Sitecore Next.js development. The Next.js guide will only display if the user wants to move to Next.js from a non-supported existing framework.
Fixes #101
=> Added Next.js guide by Meng Hak to outcome generator

src/chakra/theme/corporate/theme.ts, src/components/Prompts/ButtonGroup/ButtonGroup.tsx, src/components/Prompts/MultiSelect/MultiSelect.tsx
Removed the check for fantasy theme when displaying tooltips. Also improved the mobile view UI for ButtonGroup.tsx. Essentially brought over styling changes that were already in MultiSelect.tsx.
Fixes #122
=> Display tooltip regardless of theme choice

package-lock.json, package.json
Noticed a high number of package vulnerabilities. Performed `npm audit fix` and upgraded Cypress to version 13.
=> Update npm packages - no more vulnerabilities

src/models/OutcomeConditions.ts
Minor change so that if Forms are selected as a feature of XP being used then Send is no longer recommended.
=> Removing Forms from the check for if Send should be recommended

src/GraphQL/Queries/Prompts.gql
Issue is that when you add the new connect prompt it replaces the 10th prompt for XC questions with the disabled prompt (which doesn't help anything).  So I've upped the limit to 1000, which I doubt we'll ever reach.  There could be other content we are pulling from CH1 that could run into limits as well.
=> Fix for 11th Prompt

cypress/e2e/OutcomeFlow/outcome.cy.ts, src/lib/GameContextParser.ts, src/models/OutcomeConditions.ts, src/models/PromptMappings.ts
This change will read the data from the user and parse it into objects so that can be used in Outcomes later to make decisions on which tiles to show or which content recommendations to make. 
Additionally, this fixes the Cypress tests so that they can incorporate the new question into the flow.
=> Read data about selected integration connectors
